schema_version = "1.0.0"
id = "Quick_Asset_Saver"
version = "1.0.0"
name = "Quick Asset Saver"
tagline = "Automatic Global Asset Creation"
maintainer = "Clonephaze"
type = "add-on"
website = "https://github.com/Clonephaze/QuickAssetSaver/issues"
tags = ["User Interface", "System"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
[permissions]
files = "For reading user library paths and writing asset files"
