schema_version = "1.0.0"
id = "Quick_Asset_Saver"
version = "1.3.2"
name = "Quick Asset Saver"
tagline = "Create, Rename, Move, and Delete Asset Files Quickly"
maintainer = "Clonephaze"
type = "add-on"
website = "https://www.clonecore.net/"
tags = ["User Interface", "System"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
wheels = ["./wheels/Send2Trash-1.8.3-py3-none-any.whl"]
[permissions]
files = "For reading user library paths and writing asset files"

