schema_version = "1.0.0"
id = "Quick_Asset_Saver"
version = "2.0.0"
name = "Quick Asset Manager"
tagline = "Quickly Create, Edit, Organize, or Delete your local asset files"
maintainer = "Clonephaze"
type = "add-on"
website = "https://www.clonecore.net/"
tags = ["User Interface", "System"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
wheels = ["./wheels/Send2Trash-1.8.3-py3-none-any.whl"]
[permissions]
files = "To read and write to asset library directories"

