schema_version = "1.0.0"
id = "Quick_Asset_Saver"
version = "0.5.0"
name = "Quick Asset Saver"
tagline = "A quick way to save assets directly to your user asset library, without the need to manually copy your .blend files."
maintainer = "Clonephaze"
type = "add-on"
website = "